/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MapComponent {
        "callback": (x: string) => void;
        "userName": string;
    }
    interface SearchWorld {
        "searchText": string;
    }
}
declare global {
    interface HTMLMapComponentElement extends Components.MapComponent, HTMLStencilElement {
    }
    var HTMLMapComponentElement: {
        prototype: HTMLMapComponentElement;
        new (): HTMLMapComponentElement;
    };
    interface HTMLSearchWorldElement extends Components.SearchWorld, HTMLStencilElement {
    }
    var HTMLSearchWorldElement: {
        prototype: HTMLSearchWorldElement;
        new (): HTMLSearchWorldElement;
    };
    interface HTMLElementTagNameMap {
        "map-component": HTMLMapComponentElement;
        "search-world": HTMLSearchWorldElement;
    }
}
declare namespace LocalJSX {
    interface MapComponent {
        "callback"?: (x: string) => void;
        "userName"?: string;
    }
    interface SearchWorld {
        "onSearchWorldNameSelected"?: (event: CustomEvent<string>) => void;
        "searchText"?: string;
    }
    interface IntrinsicElements {
        "map-component": MapComponent;
        "search-world": SearchWorld;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "map-component": LocalJSX.MapComponent & JSXBase.HTMLAttributes<HTMLMapComponentElement>;
            "search-world": LocalJSX.SearchWorld & JSXBase.HTMLAttributes<HTMLSearchWorldElement>;
        }
    }
}
